### ISSUE TITLE
LOADING_SOURCE_CODE: "does not export an unmount function or array of functions

### ISSUE THREAD

**Issue by ShashiBhusha-n** [joeldenning/single-spa-es5-angularjs#2]
LOADING_SOURCE_CODE: "does not export an unmount function or array of functions

Getting this error while importing Angular 7 Application. What changes i have to made in my existing application.

**Comment by internettrans** [comment]
Hi @ShashiBhusha-n, the single-spa-es5-angularjs project is geared towards Angular 1 and ES5. If you're looking for Angular 7 examples, check out https://github.com/joeldenning/coexisting-angular-microfrontends or https://github.com/CanopyTax/single-spa-angular.

I'm closing this issue for now, but feel free to comment further or reopen if there is a bug in the code or you have questions.
